name = "Waka-phil"
description = "Waka-phil is a Hugo theme that was rewritten and rearranged while adjusting [omega-hugo](https://gethugothemes.com/products/omega/) to create a webpage."
features = ['bootstrap','responsive']

[author]
  name = "Amadeus_vn"
  homepage = "https://amas.dev/"
